title: 世远启航
subtitle: 天不遮我眼，地不埋我心
description:
author: 何世远
language: zh-CN
timezone:

theme: hexo-theme-cyanstyle

deploy:
  type: git
  repository: git@github.com:shiyuan2he/shiyuan2he.github.io.git
  branch: master

highlight:   #代码块的设置 
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 10
pagination_dir: page
